spring.application.name=ecommerce

# H2 Database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

jwt.secret=mysecretkeymysecretkeymysecretkey123
jwt.expiration=3600000

cloudinary.cloud-name=dqhowyunn
cloudinary.api-key=381658312534237
cloudinary.api-secret=BgyOtUAkVEoVm9zEhIunt7jI2z0