apiVersion: v1
kind: ConfigMap
metadata:
  name: solydshop-config
data:
  DB_URL: "jdbc:postgresql://45.55.78.201:5432/solydShopdb"
  NOTIFICATION_SERVICE_URL: "http://solydshop-notifications:8081"
  CLOUDINARY_CLOUD_NAME: "dummy-cloud"
  STRIPE_PUBLISHABLE_KEY: "pk_test_dummy"
  JWT_EXPIRATION: "3600000"
  FRONTEND_URL: "http://localhost:3000"
  CORS_ALLOWED_ORIGINS: "http://localhost:3000"
  COOKIE_SECURE: "false"
  COOKIE_SAME_SITE: "Lax"
  SPRING_PROFILES_ACTIVE: "prod"
